- hosts: localhost
  connection: local
  tags: always
  tasks:
  - homebrew:
      name: curl
      state: present
    environment:
      PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_facts.env.PATH }}
