- hosts: localhost
  connection: local
  tags: always
  become: true
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name:
        - curl
        - wget
        - golang
        - zsh
      state: latest
      
