---
# tasks file for workstation

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: setup gitconfig
  ansible.builtin.copy:
    src: files/home/.gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Add google apt signing key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add chrome repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }}] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Add hashicorp apt signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - curl
      - wget
      - golang
      - zsh
      - terraform
      - google-chrome-stable
    state: latest
    update_cache: yes