---
# tasks file for workstation

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- include_tasks: git.yml
- include_tasks: terraform.yml
- include_tasks: chrome.yml